### ISSUE TITLE
Can't initialize Sun PKCS#11 security provider

### ISSUE THREAD

**Issue by NadezdaMh** [nowina-solutions/nexu#22]
We use version 1.22 and still have this issue
The log file is attached
2019-05-30 09:45:44,205 DEBUG [AbstractSignatureTokenConnection] PKCS11 Config : 
name = SmartCarde91e3fae-8e91-4f71-b6ab-9649fc56cd2d
library = "C:\\Windows\\System32\\idprimepkcs11.dll"
slotListIndex = 0
2019-05-30 09:45:44,206 ERROR [GetCertificateFlow] Flow error
eu.europa.esig.dss.DSSException: Can't initialize Sun PKCS#11 security provider. Reason: PKCS11 not found
	at eu.europa.esig.dss.token.Pkcs11SignatureToken.getKeyStore(Pkcs11SignatureToken.java:196)
	at eu.europa.esig.dss.token.AbstractKeyStoreTokenConnection.getKeys(AbstractKeyStoreTokenConnection.java:23)
	at lu.nowina.nexu.generic.Pkcs11SignatureTokenAdapter.getKeys(Pkcs11SignatureTokenAdapter.java:114)
	at lu.nowina.nexu.flow.operation.SelectPrivateKeyOperation.perform(SelectPrivateKeyOperation.java:89)
	at lu.nowina.nexu.flow.GetCertificateFlow.process(GetCertificateFlow.java:104)
	at lu.nowina.nexu.flow.GetCertificateFlow.process(GetCertificateFlow.java:49)
	at lu.nowina.nexu.flow.Flow.execute(Flow.java:55)
	at lu.nowina.nexu.InternalAPI.lambda$executeRequest$0(InternalAPI.java:195)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.security.KeyStoreException: PKCS11 not found

**Comment by NadezdaMh** [comment]
My issue was fixed with extra startup parameters (-Djava.security.debug=sunpkcs11,pkcs11)
