### ISSUE TITLE
Localized Windows installation: java.lang.IllegalStateException: Cannot match pattern with netstat result

### ISSUE THREAD

**Issue by mserve** [nowina-solutions/nexu#29]
Doing requests to Nexu fail with status code 500, if I run a console windows I can see following message

```
2020-04-08 13:38:01,598 [WARN|org.eclipse.jetty.server.HttpChannel|HttpChannel|qtp14189638-23] //127.0.0.1:9795/nexu-info
java.lang.IllegalStateException: Cannot match pattern with netstat result
        at lu.nowina.nexu.jetty.CheckUserRequestProcessor.getPID(CheckUserRequestProcessor.java:92)
        at lu.nowina.nexu.jetty.CheckUserRequestProcessor.returnNullIfValid(CheckUserRequestProcessor.java:76)
        at lu.nowina.nexu.jetty.RequestProcessor.handle(RequestProcessor.java:98)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Unknown Source)
2020-04-08 13:38:28,118 [ERROR|lu.nowina.nexu.jetty.CheckUserRequestProcessor|CheckUserRequestProcessor|qtp14189638-23] Pattern \s+TCP\s+[0-9a-f\.]+:50341\s+[0-9a-f\.:]+\s+ESTABLISHED\s+([0-9]+) cannot match
Aktive Verbindungen

  Proto  Lokale Adresse         Remoteadresse          Status           PID
  TCP    127.0.0.1:9795         127.0.0.1:50297        WARTEND         0
  TCP    127.0.0.1:9795         127.0.0.1:50319        WARTEND         0
  TCP    127.0.0.1:9795         127.0.0.1:50341        HERGESTELLT     9976
...
```

As I run Nexu on a German Windows 10 platform, this regex pattern is failing

**Comment by mserve** [comment]
Added a fix using JNA to access the TCP connections via WIN32 IPHlpAPI (see #30)
