### ISSUE TITLE
Fail to sign with Estonia Id-Card

### ISSUE THREAD

**Issue by ticapix** [nowina-solutions/nexu#52]
With Windows 11, and the Estonian ID-Card, using <https://ec.europa.eu/cefdigital/DSS/webapp-demo/sign-a-digest>

Loading `C:\Windows\System32\onepin-opensc-pkcs11.dll` (0.21.0.0) from the latest eID software install (4.2.9.98)

It fails just after asking for the PIN code. Here is the log.

```text
2021-10-17 21:03:00,911 INFO  [CheckUserRequestProcessor] User for pid 2688: ticap
2021-10-17 21:03:00,912 INFO  [RequestProcessor] Request /nexu-info
2021-10-17 21:03:01,004 INFO  [CheckUserRequestProcessor] User for pid 2688: ticap
2021-10-17 21:03:01,004 INFO  [RequestProcessor] Request /nexu.js
2021-10-17 21:05:24,394 INFO  [SystrayMenu] Exiting...
2021-10-17 21:05:24,395 INFO  [NexUApp] Stopping application...
2021-10-17 21:05:24,398 INFO  [JettyListAwareServerConnector] Stopped JettyListAwareServerConnector@1bf07bd{HTTP/1.1,[http/1.1]}{kubernetes.docker.internal:9795}
2021-10-17 21:05:24,399 INFO  [JettyListAwareServerConnector] Stopped JettyListAwareServerConnector@171b295{SSL,[ssl, http/1.1]}{kubernetes.docker.internal:9895}
2021-10-17 21:05:25,711 DEBUG [CardDetector] Context was released successfully.
2021-10-17 21:06:44,625 INFO  [NexuLauncher] No http://127.0.0.1:9795/nexu-info detected, connect timed out
2021-10-17 21:06:45,118 INFO  [NexUApp] Load database from C:\Users\ticap\AppData\Local\Nowina\NexU\store.xml
2021-10-17 21:06:45,215 INFO  [APIBuilder]  + Plugin lu.nowina.nexu.keystore.KeystorePlugin
2021-10-17 21:06:45,217 INFO  [APIBuilder]  + Plugin lu.nowina.nexu.https.HttpsPlugin
2021-10-17 21:06:45,220 INFO  [HttpsPlugin] Verify if keystore is ready
2021-10-17 21:06:45,406 INFO  [HttpsPlugin] Mozilla Firefox not installed.
2021-10-17 21:06:45,490 INFO  [APIBuilder]  + Plugin lu.nowina.nexu.rest.RestHttpPlugin
2021-10-17 21:06:45,492 INFO  [APIBuilder]  + Plugin lu.nowina.nexu.windows.keystore.WindowsKeystorePlugin
2021-10-17 21:06:45,492 INFO  [NexUApp] Start Jetty
2021-10-17 21:06:45,494 INFO  [NexUApp] HttpServer is lu.nowina.nexu.https.JettyHttpsServer
2021-10-17 21:06:45,512 INFO  [log] Logging initialized @3184ms
2021-10-17 21:06:45,530 DEBUG [JettyListAwareServerConnector] JettyListAwareServerConnector@1cf0f75{HTTP/1.1,[http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@169b91c[HTTP/1.1]
2021-10-17 21:06:45,534 DEBUG [JettyListAwareServerConnector] JettyListAwareServerConnector@1cf0f75{null,[http/1.1]}{0.0.0.0:0} removed HttpConnectionFactory@169b91c[HTTP/1.1]
2021-10-17 21:06:45,534 DEBUG [JettyListAwareServerConnector] JettyListAwareServerConnector@1cf0f75{HTTP/1.1,[http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@115a214[HTTP/1.1]
2021-10-17 21:06:45,543 DEBUG [JettyListAwareServerConnector] JettyListAwareServerConnector@1016e67{SSL,[ssl]}{0.0.0.0:0} added SslConnectionFactory@1392de7{SSL->http/1.1}
2021-10-17 21:06:45,544 DEBUG [JettyListAwareServerConnector] JettyListAwareServerConnector@1016e67{SSL,[ssl, http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@17fc9ef[HTTP/1.1]
2021-10-17 21:06:45,610 INFO  [Server] jetty-9.3.z-SNAPSHOT
2021-10-17 21:06:45,621 INFO  [JettyListAwareServerConnector] Bound on port 9795
2021-10-17 21:06:45,630 INFO  [JettyListAwareServerConnector] Started JettyListAwareServerConnector@1cf0f75{HTTP/1.1,[http/1.1]}{kubernetes.docker.internal:9795}
2021-10-17 21:06:45,630 INFO  [JettyListAwareServerConnector] Bound on port 9895
2021-10-17 21:06:45,632 INFO  [SslContextFactory] x509=X509@ceaf66(localhost,h=[localhost],w=[]) for SslContextFactory@187830(null,null)
2021-10-17 21:06:45,733 INFO  [JettyListAwareServerConnector] Started JettyListAwareServerConnector@1016e67{SSL,[ssl, http/1.1]}{kubernetes.docker.internal:9895}
2021-10-17 21:06:45,733 INFO  [Server] Started @3412ms
2021-10-17 21:06:45,904 INFO  [NexUApp] Start finished
2021-10-17 21:14:39,813 INFO  [CheckUserRequestProcessor] User for pid 2688: ticap
2021-10-17 21:14:39,813 INFO  [RequestProcessor] Request /nexu.js
2021-10-17 21:14:40,085 INFO  [CheckUserRequestProcessor] User for pid 2688: ticap
2021-10-17 21:14:40,106 INFO  [CheckUserRequestProcessor] User for pid 2688: ticap
2021-10-17 21:14:40,106 INFO  [RequestProcessor] Request /rest/certificates
2021-10-17 21:14:40,106 INFO  [RequestProcessor] Process request /rest/certificates pluginId: rest
2021-10-17 21:14:40,107 INFO  [RestHttpPlugin] PathInfo /certificates
2021-10-17 21:14:40,107 INFO  [RestHttpPlugin] Payload ''
2021-10-17 21:14:40,107 INFO  [RestHttpPlugin] API call certificates
2021-10-17 21:14:40,107 INFO  [RestHttpPlugin] Call API
2021-10-17 21:14:40,119 INFO  [CardDetector] Found card in terminal 0 with ATR 3BDB960080B1FE451F830012233F536549440F9000F1.
2021-10-17 21:14:40,121 INFO  [UIOperation] Loading /fxml/product-selection.fxml view
2021-10-17 21:14:40,208 INFO  [StandaloneUIDisplay] Display BorderPane@1ba56cc in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread Thread-32
2021-10-17 21:14:40,208 INFO  [StandaloneUIDisplay] Wait on Thread Thread-32
2021-10-17 21:14:40,208 INFO  [UIOperation] Thread Thread-32 wait on ProductSelectionController
2021-10-17 21:14:40,210 WARN  [InternalAPI] Card 3BDB960080B1FE451F830012233F536549440F9000F1 is not in the personal database
2021-10-17 21:14:40,214 INFO  [InternalAPI] Product is instance of KeystoreProductAdapter
2021-10-17 21:14:40,215 INFO  [InternalAPI] Product is instance of WindowsKeystoreProductAdapter
2021-10-17 21:14:40,215 INFO  [StandaloneUIDisplay] Display BorderPane@1ba56cc in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread JavaFX Application Thread
2021-10-17 21:14:40,215 INFO  [StandaloneUIDisplay] Loading ui BorderPane@1ba56cc is a new Stage javafx.stage.Stage@130041
2021-10-17 21:14:43,083 INFO  [UIOperation] Notify from JavaFX Application Thread on ProductSelectionController
2021-10-17 21:14:43,084 INFO  [UIOperation] Thread Thread-32 resumed on ProductSelectionController
2021-10-17 21:14:43,085 WARN  [InternalAPI] Card 3BDB960080B1FE451F830012233F536549440F9000F1 is not in the personal database
2021-10-17 21:14:43,085 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@130041 and create new stage
2021-10-17 21:14:43,086 INFO  [CreateTokenOperation] 0 matching product adapters
2021-10-17 21:14:43,086 INFO  [CreateTokenOperation] Advanced mode available
2021-10-17 21:14:43,086 INFO  [UIOperation] Loading /fxml/unsupported-product.fxml view
2021-10-17 21:14:43,093 INFO  [StandaloneUIDisplay] Display BorderPane[id=AnchorPane, styleClass=unsupported-product] in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread Thread-32
2021-10-17 21:14:43,093 INFO  [StandaloneUIDisplay] Wait on Thread Thread-32
2021-10-17 21:14:43,093 INFO  [UIOperation] Thread Thread-32 wait on UnsupportedProductController
2021-10-17 21:14:43,094 INFO  [StandaloneUIDisplay] Display BorderPane[id=AnchorPane, styleClass=unsupported-product] in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread JavaFX Application Thread
2021-10-17 21:14:43,095 INFO  [StandaloneUIDisplay] Loading ui BorderPane[id=AnchorPane, styleClass=unsupported-product] is a new Stage javafx.stage.Stage@1be4e4f
2021-10-17 21:14:44,172 INFO  [UIOperation] Notify from JavaFX Application Thread on UnsupportedProductController
2021-10-17 21:14:44,172 INFO  [UIOperation] Thread Thread-32 resumed on UnsupportedProductController
2021-10-17 21:14:44,172 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@1be4e4f and create new stage
2021-10-17 21:14:44,172 INFO  [CreateTokenOperation] Advanced mode
2021-10-17 21:14:44,172 INFO  [CreateTokenOperation] Advanced mode selected
2021-10-17 21:14:44,172 INFO  [UIOperation] Loading /fxml/api-selection.fxml view
2021-10-17 21:14:44,190 INFO  [StandaloneUIDisplay] Display BorderPane@1a6c434 in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread Thread-32
2021-10-17 21:14:44,191 INFO  [StandaloneUIDisplay] Wait on Thread Thread-32
2021-10-17 21:14:44,192 INFO  [UIOperation] Thread Thread-32 wait on APISelectionController
2021-10-17 21:14:44,191 INFO  [StandaloneUIDisplay] Display BorderPane@1a6c434 in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread JavaFX Application Thread
2021-10-17 21:14:44,192 INFO  [StandaloneUIDisplay] Loading ui BorderPane@1a6c434 is a new Stage javafx.stage.Stage@2a46ae
2021-10-17 21:14:46,252 INFO  [UIOperation] Notify from JavaFX Application Thread on APISelectionController
2021-10-17 21:14:46,253 INFO  [UIOperation] Thread Thread-32 resumed on APISelectionController
2021-10-17 21:14:46,253 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@2a46ae and create new stage
2021-10-17 21:14:46,254 INFO  [CardDetector] Found card in terminal 0 with ATR 3BDB960080B1FE451F830012233F536549440F9000F1.
2021-10-17 21:14:46,254 INFO  [UIOperation] Loading /fxml/pkcs11-params.fxml view
2021-10-17 21:14:46,275 INFO  [StandaloneUIDisplay] Display BorderPane@174600f in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread Thread-32
2021-10-17 21:14:46,276 INFO  [StandaloneUIDisplay] Wait on Thread Thread-32
2021-10-17 21:14:46,276 INFO  [UIOperation] Thread Thread-32 wait on Pkcs11ParamsController
2021-10-17 21:14:46,276 INFO  [StandaloneUIDisplay] Display BorderPane@174600f in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread JavaFX Application Thread
2021-10-17 21:14:46,276 INFO  [StandaloneUIDisplay] Loading ui BorderPane@174600f is a new Stage javafx.stage.Stage@d33ec5
2021-10-17 21:14:56,444 INFO  [UIOperation] Notify from JavaFX Application Thread on Pkcs11ParamsController
2021-10-17 21:14:56,444 INFO  [UIOperation] Thread Thread-32 resumed on Pkcs11ParamsController
2021-10-17 21:14:56,445 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@d33ec5 and create new stage
2021-10-17 21:14:56,458 INFO  [Pkcs11SignatureTokenAdapter] Lib C:\Windows\System32\onepin-opensc-pkcs11.dll
2021-10-17 21:14:56,459 DEBUG [AbstractSignatureTokenConnection] PKCS11 Config : 
name = SmartCardc223cd6f-99e1-45be-b94b-24b13f400c79
library = "C:\\Windows\\System32\\onepin-opensc-pkcs11.dll"
slotListIndex = 0
2021-10-17 21:14:57,508 INFO  [StandaloneUIDisplay] Request password
2021-10-17 21:14:57,508 INFO  [UIOperation] Loading /fxml/password-input.fxml view
2021-10-17 21:14:57,522 INFO  [StandaloneUIDisplay] Display BorderPane@d3eee7 in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread Thread-32
2021-10-17 21:14:57,522 INFO  [StandaloneUIDisplay] Wait on Thread Thread-32
2021-10-17 21:14:57,522 INFO  [StandaloneUIDisplay] Display BorderPane@d3eee7 in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread JavaFX Application Thread
2021-10-17 21:14:57,522 INFO  [UIOperation] Thread Thread-32 wait on PasswordInputController
2021-10-17 21:14:57,523 INFO  [StandaloneUIDisplay] Loading ui BorderPane@d3eee7 is a new Stage javafx.stage.Stage@9b3ba3
2021-10-17 21:15:05,302 INFO  [UIOperation] Notify from JavaFX Application Thread on PasswordInputController
2021-10-17 21:15:05,302 INFO  [UIOperation] Thread Thread-32 resumed on PasswordInputController
2021-10-17 21:15:05,303 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@9b3ba3 and create new stage
2021-10-17 21:15:05,422 ERROR [GetCertificateFlow] Flow error
eu.europa.esig.dss.DSSException: Can't initialize Sun PKCS#11 security provider. Reason: load failed
	at eu.europa.esig.dss.token.Pkcs11SignatureToken.getKeyStore(Pkcs11SignatureToken.java:196)
	at eu.europa.esig.dss.token.AbstractKeyStoreTokenConnection.getKeys(AbstractKeyStoreTokenConnection.java:23)
	at lu.nowina.nexu.generic.Pkcs11SignatureTokenAdapter.getKeys(Pkcs11SignatureTokenAdapter.java:114)
	at lu.nowina.nexu.flow.operation.SelectPrivateKeyOperation.perform(SelectPrivateKeyOperation.java:89)
	at lu.nowina.nexu.flow.GetCertificateFlow.process(GetCertificateFlow.java:104)
	at lu.nowina.nexu.flow.GetCertificateFlow.process(GetCertificateFlow.java:49)
	at lu.nowina.nexu.flow.Flow.execute(Flow.java:55)
	at lu.nowina.nexu.InternalAPI.lambda$executeRequest$15(InternalAPI.java:195)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: load failed
	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:858)
	at java.security.KeyStore.load(Unknown Source)
	at eu.europa.esig.dss.token.Pkcs11SignatureToken.getKeyStore(Pkcs11SignatureToken.java:170)
	... 11 more
Caused by: javax.security.auth.login.FailedLoginException
	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1234)
	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:849)
	... 13 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_PIN_INCORRECT
	at sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1222)
	... 15 more
2021-10-17 21:15:05,424 INFO  [UIOperation] Loading /fxml/provide-feedback.fxml view
2021-10-17 21:15:05,428 INFO  [StandaloneUIDisplay] Display BorderPane@1a4a3c2 in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread Thread-32
2021-10-17 21:15:05,428 INFO  [StandaloneUIDisplay] Wait on Thread Thread-32
2021-10-17 21:15:05,428 INFO  [StandaloneUIDisplay] Display BorderPane@1a4a3c2 in display lu.nowina.nexu.StandaloneUIDisplay@1e8379f from Thread JavaFX Application Thread
2021-10-17 21:15:05,428 INFO  [UIOperation] Thread Thread-32 wait on ProvideFeedbackController
2021-10-17 21:15:05,429 INFO  [StandaloneUIDisplay] Loading ui BorderPane@1a4a3c2 is a new Stage javafx.stage.Stage@37afc3
2021-10-17 21:15:09,128 INFO  [UIOperation] Notify from JavaFX Application Thread on ProvideFeedbackController
2021-10-17 21:15:09,128 INFO  [UIOperation] Thread Thread-32 resumed on ProvideFeedbackController
2021-10-17 21:15:09,129 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@37afc3 and create new stage
2021-10-17 21:15:09,243 INFO  [StandaloneUIDisplay] Hide stage javafx.stage.Stage@423d4d and create new stage
2021-10-17 21:15:09,243 ERROR [InternalAPI] Cannot execute request
java.util.concurrent.ExecutionException: eu.europa.esig.dss.DSSException: Can't initialize Sun PKCS#11 security provider. Reason: load failed
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at lu.nowina.nexu.InternalAPI.executeRequest(InternalAPI.java:200)
	at lu.nowina.nexu.InternalAPI.getCertificate(InternalAPI.java:233)
	at lu.nowina.nexu.rest.RestHttpPlugin.getCertificates(RestHttpPlugin.java:165)
	at lu.nowina.nexu.rest.RestHttpPlugin.process(RestHttpPlugin.java:76)
	at lu.nowina.nexu.jetty.RequestProcessor.httpPlugin(RequestProcessor.java:183)
	at lu.nowina.nexu.jetty.RequestProcessor.handle(RequestProcessor.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
Caused by: eu.europa.esig.dss.DSSException: Can't initialize Sun PKCS#11 security provider. Reason: load failed
	at eu.europa.esig.dss.token.Pkcs11SignatureToken.getKeyStore(Pkcs11SignatureToken.java:196)
	at eu.europa.esig.dss.token.AbstractKeyStoreTokenConnection.getKeys(AbstractKeyStoreTokenConnection.java:23)
	at lu.nowina.nexu.generic.Pkcs11SignatureTokenAdapter.getKeys(Pkcs11SignatureTokenAdapter.java:114)
	at lu.nowina.nexu.flow.operation.SelectPrivateKeyOperation.perform(SelectPrivateKeyOperation.java:89)
	at lu.nowina.nexu.flow.GetCertificateFlow.process(GetCertificateFlow.java:104)
	at lu.nowina.nexu.flow.GetCertificateFlow.process(GetCertificateFlow.java:49)
	at lu.nowina.nexu.flow.Flow.execute(Flow.java:55)
	at lu.nowina.nexu.InternalAPI.lambda$executeRequest$15(InternalAPI.java:195)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.IOException: load failed
	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:858)
	at java.security.KeyStore.load(Unknown Source)
	at eu.europa.esig.dss.token.Pkcs11SignatureToken.getKeyStore(Pkcs11SignatureToken.java:170)
	... 11 more
Caused by: javax.security.auth.login.FailedLoginException
	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1234)
	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:849)
	... 13 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_PIN_INCORRECT
	at sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1222)
	... 15 more
```

I checked the PIN several time and it works fine in the DigiDoc app.

PS: the same demo website, payload, option works fine with a eiDAS Gemalto key and `MSCAPI`

**Comment by ticapix** [comment]
With his consent, sharing the answer from Margus and closing the issue.

> Hello Pierre
>
> I recommend using https://web-eid.eu/ for Estonian eID cards. hwcrypto was old solution that is being migrate away from, by itself its quite easy to use https://hwcrypto.github.io/demo/
> 
> NexU is a bit abandoned and not a fully "finished" project. If you want NexU then we need to debug it with you. You need to tell me the steps you used to reproduce it. 
> [...]. Depending on how exactly you are using it the work estimation is half a day or full day.
> 
> We also have an eID Easy SaaS solution where national supported eID cards and USB tokens with qualified certificates the hash signature price is 0.15EUR per signature. There are also other methods that we constantly keep on adding. Demo is at https://demo.eideasy.com
>
>-- 
>eID and eSignature developer tools
>Margus Pala
>CEO
> [...]

**Comment by ticapix** [comment]
Hi,

I migrated and integrated https://web-eid.eu/

Best,
Pierre
