### ISSUE TITLE
Failing JREVendorTest in nexu-api

### ISSUE THREAD

**Issue by SeSodesa** [nowina-solutions/nexu#54]
Trying to compile the project on macOS Catalina 10.15.7 with

	openjdk version "1.8.0_292"
	OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
	OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

and Maven 3.8.4 results in the following compilation output:

	[INFO] Error stacktraces are turned on.
	[INFO] Scanning for projects...
	[INFO] ------------------------------------------------------------------------
	[INFO] Reactor Build Order:
	[INFO]
	[INFO] NexU                                                               [pom]
	[INFO] nexu-api                                                           [jar]
	[INFO] nexu-model                                                         [jar]
	[INFO] nexu-util                                                          [jar]
	[INFO] nexu-core                                                          [jar]
	[INFO] nexu-rest-plugin                                                   [jar]
	[INFO] nexu-standalone                                                    [jar]
	[INFO] nexu-https-plugin                                                  [jar]
	[INFO] nexu-windows-keystore-plugin                                       [jar]
	[INFO] nexu-multi-user-support                                            [jar]
	[INFO] nexu-app                                                           [jar]
	[INFO] nexu-bundle                                                        [pom]
	[INFO] nexu-public-object-model                                           [jar]
	[INFO]
	[INFO] ------------------------< lu.nowina.apps:nexu >-------------------------
	[INFO] Building NexU 1.22                                                [1/13]
	[INFO] --------------------------------[ pom ]---------------------------------
	[INFO]
	[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nexu ---
	[INFO]
	[INFO] --- maven-install-plugin:2.5.2:install-file (install-dorkbox) @ nexu ---
	[INFO] pom.xml not found in SystemTray-3.0.RC6.jar
	[INFO] Installing /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-standalone/lib/SystemTray-3.0.RC6.jar to /Users/soderhos/.m2/repository/com/dorkbox/SystemTray/3.0.RC6/SystemTray-3.0.RC6.jar
	[INFO] Installing /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-standalone/lib/SystemTray-3.0.RC6-sources.jar to /Users/soderhos/.m2/repository/com/dorkbox/SystemTray/3.0.RC6/SystemTray-3.0.RC6-sources.jar
	[INFO]
	[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ nexu ---
	[INFO] Installing /Users/soderhos/Downloads/nexu-nexu-1.22/pom.xml to /Users/soderhos/.m2/repository/lu/nowina/apps/nexu/1.22/nexu-1.22.pom
	[INFO]
	[INFO] ----------------------< lu.nowina.apps:nexu-api >-----------------------
	[INFO] Building nexu-api 1.22                                            [2/13]
	[INFO] --------------------------------[ jar ]---------------------------------
	[INFO]
	[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nexu-api ---
	[INFO] Deleting /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target
	[INFO]
	[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ nexu-api ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] Copying 3 resources
	[INFO]
	[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ nexu-api ---
	[INFO] Changes detected - recompiling the module!
	[INFO] Compiling 51 source files to /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target/classes
	[WARNING] /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/src/main/java/lu/nowina/nexu/api/AppConfig.java: /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/src/main/java/lu/nowina/nexu/api/AppConfig.java uses or overrides a deprecated API.
	[WARNING] /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/src/main/java/lu/nowina/nexu/api/AppConfig.java: Recompile with -Xlint:deprecation for details.
	[INFO]
	[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ nexu-api ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/src/test/resources
	[INFO]
	[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ nexu-api ---
	[INFO] Changes detected - recompiling the module!
	[INFO] Compiling 7 source files to /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target/test-classes
	[INFO]
	[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ nexu-api ---
	[INFO] Surefire report directory: /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target/surefire-reports

	-------------------------------------------------------
	 T E S T S
	-------------------------------------------------------
	Running lu.nowina.nexu.api.ConfigurationManagerTest
	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
	SLF4J: Defaulting to no-operation (NOP) logger implementation
	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
	Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.261 sec
	Running lu.nowina.nexu.api.OSTest
	Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
	Running lu.nowina.nexu.api.plugin.HttpResponseTest
	Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
	Running lu.nowina.nexu.api.JREVendorTest
	Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
	test1(lu.nowina.nexu.api.JREVendorTest)  Time elapsed: 0.001 sec  <<< FAILURE!
	java.lang.AssertionError: Values should be different. Actual: NOT_RECOGNIZED
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failEquals(Assert.java:185)
		at org.junit.Assert.assertNotEquals(Assert.java:161)
		at org.junit.Assert.assertNotEquals(Assert.java:175)
		at lu.nowina.nexu.api.JREVendorTest.test1(JREVendorTest.java:26)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
		at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
		at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

	Running lu.nowina.nexu.api.EnvironmentInfoTest
	Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
	Running lu.nowina.nexu.api.ArchTest
	Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
	Running lu.nowina.nexu.api.CertificateFilterHelperTest
	Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.029 sec

	Results :

	Failed tests:   test1(lu.nowina.nexu.api.JREVendorTest): Values should be different. Actual: NOT_RECOGNIZED

	Tests run: 19, Failures: 1, Errors: 0, Skipped: 0

	[INFO] ------------------------------------------------------------------------
	[INFO] Reactor Summary for NexU 1.22:
	[INFO]
	[INFO] NexU ............................................... SUCCESS [  0.240 s]
	[INFO] nexu-api ........................................... FAILURE [  1.834 s]
	[INFO] nexu-model ......................................... SKIPPED
	[INFO] nexu-util .......................................... SKIPPED
	[INFO] nexu-core .......................................... SKIPPED
	[INFO] nexu-rest-plugin ................................... SKIPPED
	[INFO] nexu-standalone .................................... SKIPPED
	[INFO] nexu-https-plugin .................................. SKIPPED
	[INFO] nexu-windows-keystore-plugin ....................... SKIPPED
	[INFO] nexu-multi-user-support ............................ SKIPPED
	[INFO] nexu-app ........................................... SKIPPED
	[INFO] nexu-bundle ........................................ SKIPPED
	[INFO] nexu-public-object-model ........................... SKIPPED
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time:  2.216 s
	[INFO] Finished at: 2021-12-16T14:57:01+02:00
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project nexu-api: There are test failures.
	[ERROR]
	[ERROR] Please refer to /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target/surefire-reports for the individual test results.
	[ERROR] -> [Help 1]
	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project nexu-api: There are test failures.

	Please refer to /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target/surefire-reports for the individual test results.
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
	    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
	    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
	    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
	    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
	    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
	    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
	    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke (Method.java:498)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
	Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

	Please refer to /Users/soderhos/Downloads/nexu-nexu-1.22/nexu-api/target/surefire-reports for the individual test results.
	    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:83)
	    at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary (SurefirePlugin.java:176)
	    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:150)
	    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:650)
	    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:586)
	    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
	    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
	    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
	    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
	    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
	    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
	    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
	    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke (Method.java:498)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
	[ERROR]
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR]
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
	[ERROR]
	[ERROR] After correcting the problems, you can resume the build with the command
	[ERROR]   mvn <args> -rf :nexu-api

Looking at the surefire reports of `nexu-api`, it can be seen that the main cause is a failing JREVendorTest:

	-------------------------------------------------------------------------------
	Test set: lu.nowina.nexu.api.JREVendorTest
	-------------------------------------------------------------------------------
	Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
	test1(lu.nowina.nexu.api.JREVendorTest)  Time elapsed: 0 sec  <<< FAILURE!
	java.lang.AssertionError: Values should be different. Actual: NOT_RECOGNIZED
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failEquals(Assert.java:185)
		at org.junit.Assert.assertNotEquals(Assert.java:161)
		at org.junit.Assert.assertNotEquals(Assert.java:175)
		at lu.nowina.nexu.api.JREVendorTest.test1(JREVendorTest.java:26)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
		at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
		at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

This is not a PATH issue, as my system is able to locate my current Java installation and hence it must be my Java *version* that is not correct. What Java version must I use to be able to compile NexU on a Mac?

**Comment by SeSodesa** [comment]
Ah, looks like an Oracle-specific Java distribution is required, based on the following snippet located in nexu-api → src → main → java → lu → nowina → nexu → api → JREVendor.java, lines 38–43:

	if (jreVendor.toLowerCase().contains("oracle")) {
		return ORACLE;
	} else {
		logger.warn("JRE not recognized " + jreVendor);
		return NOT_RECOGNIZED;
	}

This can be disabled with a simple addition of a short-circuiting boolean operator:

	if (true || jreVendor.toLowerCase().contains("oracle")) {
		return ORACLE;
	} else {
		logger.warn("JRE not recognized " + jreVendor);
		return NOT_RECOGNIZED;
	}

Compilation can then proceed. The next question then is, why is OpenJDK disliked so much? Licensing issues?
