### ISSUE TITLE
Failure when signing with SHA256

### ISSUE THREAD

**Issue by ChalaChalashas** [nowina-solutions/nexu#6]
Hello,

I'm trying to sign document using NexU on DSS demo app.
I'm using this card: [GemXpresso R4 72K](https://www.cryptsoft.com/fips140/vendors/140sp771.pdf)
Everything is ok with SHA1, but when trying to sign with  SHA256 error window pops up, stacktrace:

---EDIT---
Correct stack trace
```
2016-11-21 16:24:30,461 [INFO|eu.europa.esig.dss.token.AbstractSignatureTokenConnection|AbstractSignatureTokenConnection|Thread-16] Signature algorithm: RSA/SHA256
2016-11-21 16:24:30,885 [ERROR|lu.nowina.nexu.flow.SignatureFlow|SignatureFlow|Thread-16] Flow error
eu.europa.esig.dss.DSSException: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
        at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:64)
        at lu.nowina.nexu.generic.Pkcs11SignatureTokenAdapter.sign(Pkcs11SignatureTokenAdapter.java:52)
        at lu.nowina.nexu.flow.operation.SignOperation.perform(SignOperation.java:65)
        at lu.nowina.nexu.flow.SignatureFlow.process(SignatureFlow.java:86)
        at lu.nowina.nexu.flow.SignatureFlow.process(SignatureFlow.java:43)
        at lu.nowina.nexu.flow.Flow.execute(Flow.java:55)
        at lu.nowina.nexu.InternalAPI.lambda$executeRequest$0(InternalAPI.java:200)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
        at sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:591)
        at java.security.Signature$Delegate.engineSign(Unknown Source)
        at java.security.Signature.sign(Unknown Source)
        at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:58)
        ... 10 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
        at sun.security.pkcs11.wrapper.PKCS11.C_Sign(Native Method)
        at sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:582)
        ... 13 more
```

**Comment by jlepropre** [comment]
Hello,

I was unable to reproduce the issue with my Belgian eID card and PKCS#11 plugin.

Could I ask you to check/precise the following things:
- Are you well using the latest snapshot version of NexU from the develop branch?
- Which is your environment (OS, Java version and vendor, etc.)?
- Which is your precise scenario from the start of NexU till the error?

Thanks in advance for your answer,
Best regards,
Jean.

**Comment by ChalaChalashas** [comment]
I'm using NexU version [1.7](https://github.com/nowina-solutions/nexu/tree/nexu-1.7)
OS: Windows 8.1 x64
Java: 

```
 C:\>%JAVA32% -XshowSettings:properties -version
 ..................
     java.vendor = Oracle Corporation
     java.version = 1.8.0_91
     os.arch = x86
     os.name = Windows 8.1
     os.version = 6.3
 ..................
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) Client VM (build 25.91-b15, mixed mode, sharing)
```
Scenario:
• Started nexu with x86 java 
• Installed certificate by pressing yes in promt
• Filled info in dss/NexU
![image](https://cloud.githubusercontent.com/assets/5492630/20479094/894802cc-afe5-11e6-9215-f31e628cf090.png)
• Submit
• Selected card
![image](https://cloud.githubusercontent.com/assets/5492630/20480399/fa5a0316-afea-11e6-846d-e8ba69e0c97d.png)
• Advanced configuration > PKCS11 >selected  CryptoTech Cryptocard pkcs11 driver
![image](https://cloud.githubusercontent.com/assets/5492630/20480445/38b261d0-afeb-11e6-9b02-03505bf23b81.png)
• Filled password
• Selected certificate
• Closed "...remember settings..." promt
• Ok on "Certificate was successfully retrieved." promt
• Exception, but not the same as above, that exception was because of corrupted jre installation
exception:
```
2016-11-21 16:24:30,461 [INFO|eu.europa.esig.dss.token.AbstractSignatureTokenConnection|AbstractSignatureTokenConnection|Thread-16] Signature algorithm: RSA/SHA256
2016-11-21 16:24:30,885 [ERROR|lu.nowina.nexu.flow.SignatureFlow|SignatureFlow|Thread-16] Flow error
eu.europa.esig.dss.DSSException: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
        at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:64)
        at lu.nowina.nexu.generic.Pkcs11SignatureTokenAdapter.sign(Pkcs11SignatureTokenAdapter.java:52)
        at lu.nowina.nexu.flow.operation.SignOperation.perform(SignOperation.java:65)
        at lu.nowina.nexu.flow.SignatureFlow.process(SignatureFlow.java:86)
        at lu.nowina.nexu.flow.SignatureFlow.process(SignatureFlow.java:43)
        at lu.nowina.nexu.flow.Flow.execute(Flow.java:55)
        at lu.nowina.nexu.InternalAPI.lambda$executeRequest$0(InternalAPI.java:200)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
        at sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:591)
        at java.security.Signature$Delegate.engineSign(Unknown Source)
        at java.security.Signature.sign(Unknown Source)
        at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:58)
        ... 10 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DEVICE_ERROR
        at sun.security.pkcs11.wrapper.PKCS11.C_Sign(Native Method)
        at sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:582)
        ... 13 more

```

**Comment by jlepropre** [comment]
Hello,

Is this new error appearing only with SHA-256? If so, could you please check that your PKCS#11 driver and card well supports SHA-256?

Best regards,
Jean.

**Comment by ChalaChalashas** [comment]
Just tested again, error occurs not only with SHA-256, but also with every other option in DSS except SHA-1. Driver works fine, old java applet signs with SHA-256 using the same driver.

**Comment by pvandenbroucke** [comment]
Hello,

I did some searches and I think that your driver only supports SHA-1.

Please see on the [cryptotech website](http://www.cryptotech.com.pl/Informacje/CryptoCard_Suite_zmienia_rynek_kart,content.html). I didn't find any alternative (open source driver (opensc),...). You may contact them to know if they offer any newer driver ?

Kind regards,

Pierrick

**Comment by ChalaChalashas** [comment]
Hello, 

As mentioned before, I have Java applet witch uses same driver for signing, and it works with SHA-256 fine
![image](https://cloud.githubusercontent.com/assets/5492630/20530709/e79f9a9a-b0dc-11e6-8128-507807ecacd8.png)
so I don't think that it is driver problem.

**Comment by pvandenbroucke** [comment]
Hello,

Do you talk about the old applet from the DSS project with the PKCS#11 parameters ? 

Kind regards,

Pierrick

**Comment by ChalaChalashas** [comment]
No, I think not that one, I just have an old .jar with no references to source.
I found another solution which works using same driver [Isign](https://app.isign.lt/register), they uses different approach - chrome plugin + client service, but result is the same, signature with SHA-256.
I found out that they use SHA-256 for signature algorithm, but SHA-1 for message digest, maybe that's why it does not works on NexU?

**Comment by pvandenbroucke** [comment]
Hello,

I think there're some small confusions.

On the previous screenshot, you showed the certificate properties. The selected signature algorithm  was used to sign your certificate (by the issuer). This algorithm is RSA with SHA256.

A signature algorithm is the combination of a digest algorithm (SHA-1/256/512/...) and an encryption algorithm (RSA, DSA, ECDSA,...).

Could you validate a signature produced with the old jar on http://dss.nowina.lu/validation and check the diagnostic tree tab ?

![screenshot](https://cloud.githubusercontent.com/assets/10741105/20533850/5606d12c-b0df-11e6-994c-2aa60d1df9f7.png)

Kind regards,

Pierrick

**Comment by ChalaChalashas** [comment]
Ok, it says that signature algorithm is SHA1, so I don't have any working solution. It is possible that SHA-256 may be not supported not by the driver, but by the card itself ([card documentation](https://www.cryptsoft.com/fips140/vendors/140sp771.pdf))? I will try another card tomorrow.

Kind regerds,

Paulius

**Comment by ChalaChalashas** [comment]
Hello, 

Just tested with with another ID card, and it works with SHA-256! So, the problem is in old version of Lithuanian ID card, not NexU.

Thanks for help,
Kind regards,
Paulius
